version: '3.9'
services:
  db:
    container_name: restaurant-db
    image: postgres:16.2
    ports:
      - 8599:5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_EXTENSIONS: uuid-ossp pgcrypto
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
